### PR TITLE
Adding GitHub specific instructions, to ease the workflow of people like me.

### PR DESCRIPTION
**Pull request by gl-yziquel**

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
I'd move this after the `installation` section and before `Licence` into a new section `Usage with GitHub`.

There's nothing special about github specifically that warrants mentioning these instructions early in the README.

**Comment by gl-yziquel** [comment]
Right.

Nothing special about github to put it here.

I just want it "somewhere".

**Comment by gl-yziquel** [comment]
Do tell me if the change of position of these instructions suit you.

**Comment by WhyNotHugo** [comment]
Thanks! Merged via 121616a78abeb676daaaac0f00178453d0956029

**Pull request closed without merging**
